Repository flyingcircusio/batou, pull requests merged in 2021-09, with the labels that each got.

#227 Raise an error if an internet protocol family is used but not configured.
  CHANGES.md
  doc/source/api/component.txt
  doc/source/api/exceptions.rst
  doc/source/index.txt
  examples/errors2/components/dnsproblem2/component.py
  examples/errors2/environments/errors.cfg
  src/batou/__init__.py
  src/batou/tests/test_endtoend.py
  src/batou/tests/test_utils.py
  src/batou/utils.py
Labels: enhancement, gocept

#226 Improve error message for DNS lookup semantics.
  CHANGES.md
  src/batou/tests/test_utils.py
  src/batou/utils.py
Labels: documentation

#228 Integrate `remote-pdb` to debug batou runs.
  CHANGES.md
  doc/source/user/advanced.txt
  setup.py
  src/batou/__init__.py
  src/batou/host.py
  src/batou/remote_core.py
  src/batou/tests/test_config.py
  src/batou/tests/test_remote_core.py
Labels: documentation, enhancement, gocept
